version: '2'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
    networks:
      - default
    expose:
      - "3306"
    volumes:
      - dbData:/var/lib/mysql
  app:
    image: wordpress:fpm
    networks:
      - default
    expose:
      - "9000"
    volumes:
      - appdata:/var/www/html
  web:
    image: nginx:latest
    networks:
      - default
      - frontEnd
    ports:
      - "80"
      - "443"
    volumes:
      - appdata:/var/www/html

networks:
  frontEnd:
    driver: bridge

volumes:
  appData:
    driver: local
  dbData:
    driver: local
