version: '2'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
      WORDPRESS_DB_HOST: "db:3306"
    networks:
      - default
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
  app:
    image: wordpress:fpm
    networks:
      - default
    expose:
      - "9000"
    volumes:
      - app:/var/www/html
  web:
    image: nginx:latest
    networks:
      - default
      - front
    ports:
      - "80"
      - "443"
    volumes:
      - app:/var/www/html

networks:
  front:
    driver: bridge

volumes:
  app:
    driver: local
  db:
    driver: local
