version: '2'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
    networks:
      - default
    expose:
      - "3306"
    volumes:
      - /var/lib/mysql
  app:
    image: wordpress:fpm
    links:
      - "db:mysql"
    networks:
      - default
    expose:
      - "9000"
    volumes:
      - /var/www/html
  web:
    image: nginx:latest
    networks:
      - default
    ports:
      - "80"
      - "443"
    volumes_from:
      - app:ro
